### ISSUE TITLE
image preview inside the app

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/BDRC-Lib-App#105]
# Tasks

- [ ] Show an image preview in the search results
- [ ] Show an image preview inside the work and workpart detail 
- [ ] On click, open a lightbox allowing zoom and pan of a larger image

# thumbnail & Preview

https://iiif.bdrc.io/bdr:W8CZ40::thumbnail/full/!2000,195/0/default.dflt

in search results, fit into a box that is always the same hight, using black for any empty space in order to prevent page jumps

**Comment by subsystem7** [comment]
Original request:


> ideally, in the work record view, the app would display a few images (that can be lower res than the original) so that users can be sure that this is indeed the version they're looking for.
> 
> I think the easiest solution will be to download the manifest for a work or a work part (see the [API](https://github.com/buda-base/buda-iiif-presentation/blob/master/API.md)), and construct the image URLs from there.

**Comment by eroux** [comment]
I've created an endpoint that combines both (through IIIF). For instance if you want the IIIF image service for the thumbnail of W22084, it's on `https://iiif.bdrc.io/bdr:W22084::thumbnail/` so that you can then query for a specific size (for thumbnail or for full display) using the [IIIF image request parameters](https://iiif.io/api/image/2.1/#image-request-parameters). For instance on BUDA we use `!2000,195` as the `size` parameter, so that the image returned is less than 2000px wide and less than 195px high, as in 

```
https://iiif.bdrc.io/bdr:W8CZ40::thumbnail/full/!2000,195/0/default.dflt
```

Note that for the purpose of this specific task, it's best to use the non-standard `dflt` format that I've implemented. So you can use the same endpoint for the image preview and the thumbnail in the search, at the same or different sizes.
